### ISSUE TITLE
Stop the text in chat from showing up when teleporting

### ISSUE THREAD

**Issue by notMae3** [Sjouwer/tp-utils#5]
I find it annoying and didn't find an option for it

**Comment by Sjouwer** [comment]
This mod doesn't send a message when you succesfully teleport (only when it fails to find a spot to tp to). Any message you recieve is either the default minecraft message you always get when teleporting in singleplayer or a message that the server you play on is sending you. I might be able to block the default minecraft message, however if you play on a server that sends you a custom message, then I won't be able to block it. Could you maybe elaborate what the exact message is?

**Comment by notMae3** [comment]
I managed to fix it by setting /gamerule sendCommandFeedback false. This issue seems to not be related to the mod. Sorry for taking up your time.
